language: go
sudo: false
go:
  - 1.5
  - 1.6
  - 1.7
  - master

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - nvm install 6 && nvm use 6

install:
  - echo `npm -v`
  - echo `node -v`
  - export GO15VENDOREXPERIMENT=1
  - go get github.com/rakyll/statik
  - go install github.com/rakyll/statik
  - cd dashboard/js && npm install && npm run build && cd ../..
  - statik -src=dashboard/js/build -dest=dashboard
  - go get github.com/Masterminds/glide
  - go install github.com/Masterminds/glide
  - glide up

script:
  - ./.travis.gofmt.sh
  - make guerrillad
  - go test ./tests
  - go test
  - go test ./cmd/guerrillad
  - go test ./response
