language: go
sudo: false
go:
  - 1.7
  - 1.8
  - 1.9
  - 1.10.x
  - master

install:
  - export GO15VENDOREXPERIMENT=1
  - godep ensure

script:
  - ./.travis.gofmt.sh
  - make guerrillad
  - make test
