language: go
sudo: false
go:
  - 1.7
  - 1.8
  - 1.9
  - 1.10.x
  - master

install:
  - export GO15VENDOREXPERIMENT=1
    # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

script:
  - ./.travis.gofmt.sh
  - make guerrillad
  - make test
